server:
  port: 8091
#  tomcat:
#    max-threads: 1
spring:
  application:
    name: shop-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.134.101:3306/shopserver?createDatabaseIfNotExist=true&Timezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: com.neuedu.UTF8MySql5Dialect
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.134.101:8848
    sentinel:
      transport:
        dashboard: 192.168.134.101:8858
        port: 8719
        clientIp: 192.168.134.1 #如果是docker部署sentienl dashboard需要添加此配置，否则iptables可能无法正确识别宿主机ip
      eager: true   #开启饥饿模式
#      filter:
#        enabled: false
shop-product: # 调用的提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  sentinel:
    enabled: true
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000